[package]
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
categories = ["game-engines", "rendering"]
description = "A rendering library for large scale terrains"
documentation = "https://docs.rs/terra"
edition = "2021"
homepage = "https://github.com/fintelia/terra"
license = "Apache-2.0"
name = "terra"
readme = "README.md"
repository = "https://github.com/fintelia/terra"
version = "0.3.0"
resolver = "2"

[[bin]]
name = "preview"
path = "bin/preview.rs"

[dependencies]
anyhow = "1.0.57"
astro = "2.0.0"
async-trait = "0.1.56"
atomicwrites = "0.3.1"
basis-universal = "0.2.0"
bincode = "1.3.3"
bit-vec = "0.6.3"
bytemuck = { version = "1.9.1", features = ["extern_crate_alloc"] }
byteorder = "1.4.3"
cgmath = { version = "0.18.0", features = ["mint", "serde"] }
crossbeam = "0.8.1"
curl = "0.4.43"
dirs = "4.0.0"
env_logger = "0.9.0"
fnv = "1.0.7"
futures = "0.3.21"
gilrs = "0.9.0"
hyper = { version = "0.14.19", features = ["full"] }
hyper-tls = "0.5.0"
image = "0.24.2"
indicatif = "0.16.2"
itertools = "0.10.3"
lazy_static = "1.4.0"
linked-hash-map = "0.5.4"
log = "0.4.17"
lru = "0.7.6"
lz4 = "1.23.3"
maplit = "1.0.2"
memmap = "0.7.0"
mint = "0.5.9"
num = "0.4.0"
num-traits = "0.2.15"
open-location-code = "0.1.0"
petgraph = "0.6.2"
planetcam = { path = "planetcam" }
quick-xml = { version = "0.23.0", features = ["serialize"] }
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.5.3"
rshader = { path = "rshader", features = ["dynamic_shaders"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
sled = "0.34.7"
smaa = { version = "0.6.0", optional = true }
snap = "1.0.5"
sscanf = "0.2.1"
structopt = "0.3.26"
thiserror = "1.0.31"
tiff = { git = "https://github.com/image-rs/image-tiff", rev = "a780da0b34429da9348a898f49565d8c3387e950" }
tilefmt = { path = "tilefmt" }
tokio = { version = "1.19.2", features = ["fs", "macros", "sync", "rt", "rt-multi-thread", "io-util"] }
tokio-stream = "0.1.9"
types = { path = "types" }
vec_map = { version = "0.8.2", features = ["serde"] }
wgpu = { version = "0.12.0", features = ["spirv"] }
winit = "0.26.1"
zip = "0.6.2"

[dev-dependencies]
approx = "0.5.1"

[features]
trace = ["wgpu/trace"]
small-trace = ["trace"]
soft-float64 = []

[profile]
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true
incremental = true

[patch.crates-io]
naga = { git = "https://github.com/gfx-rs/naga", rev = "a45b9a6" }
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "87102ccdf5e8e5455f22dee12617c37b8c00bd08" }
