[package]
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
categories = ["game-engines", "rendering"]
description = "A rendering library for large scale terrains"
documentation = "https://docs.rs/terra"
edition = "2018"
homepage = "https://github.com/fintelia/terra"
license = "Apache-2.0"
name = "terra"
readme = "README.md"
repository = "https://github.com/fintelia/terra"
version = "0.3.0"
resolver = "2"

[[bin]]
name = "preview"
path = "bin/preview.rs"

[dependencies]
anyhow = "1.0.36"
astro = "2.0.0"
async-trait = "0.1.42"
atomicwrites = "0.2.5"
basis-universal = "0.1.1"
bincode = "1.3.1"
bit-vec = "0.6.3"
bytemuck = "1.4.1"
byteorder = "1.3.4"
cgmath = { version = "0.18.0", features = ["mint", "serde"] }
crossbeam = "0.8.0"
curl = "0.4.34"
dirs = "3.0.1"
env_logger = "0.9.0"
fnv = "1.0.7"
futures = "0.3.8"
gilrs = "0.8.0"
hyper = { version = "0.14.1", features = ["full"] }
hyper-tls = "0.5"
image = "0.23.12"
indicatif = "0.15.0"
itertools = "0.9.0"
lazy_static = "1.4.0"
linked-hash-map = "0.5.3"
log = "0.4.14"
lru-cache = "0.1.2"
lz4 = "1.23.2"
maplit = "1.0.2"
memmap = "0.7.0"
mint = "0.5.6"
num = "0.3.1"
open-location-code = "0.1.0"
petgraph = "0.5.1"
rand = "0.8.0"
rand_distr = "0.4.0"
rayon = "1.5.0"
rshader = { path = "rshader", features = ["dynamic_shaders"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
sha2 = "0.9.2"
sled = "0.34.6"
#smaa = { version = "0.4.0", optional = true }
snap = "1.0.3"
structopt = "0.3.21"
thiserror = "1.0.22"
tiff = { git = "https://github.com/image-rs/image-tiff" }
tokio = { version = "1.0.0", features = ["fs", "macros", "sync", "rt", "rt-multi-thread", "io-util"] }
tokio-stream = "0.1.7"
vec_map = { version = "0.8.2", features = ["serde"] }
wgpu = { version = "0.11.0", features = ["spirv"] }
winit = "0.25.0"
zip = "0.5.9"

[dev-dependencies]
approx = "0.4.0"

[features]
trace = ["wgpu/trace"]
small-trace = ["trace"]
soft-float64 = []

[profile]
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true

[patch.crates-io]
naga = { git = "https://github.com/fintelia/naga", rev = "f3949186875e791de0c7223e47af4237ae050f9e" }
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "7e00abf651efb967c3eee5a94c0185f98aa8527c" }

[patch."https://github.com/gfx-rs/naga"]
naga = { git = "https://github.com/fintelia/naga", rev = "f3949186875e791de0c7223e47af4237ae050f9e" }
