[package]
name = "rshader"
version = "0.2.0"
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
license = "Apache-2.0"
description = "A simply library for reloading shaders at runtime"
repository = "https://github.com/fintelia/terra"
homepage = "https://github.com/fintelia/terra"
categories = ["game-engines", "rendering"]
edition = "2018"

[dependencies]
anyhow = "1.0.33"
generic-array = "0.14.4"
naga = "0.4.0"
notify = "4.0.15"
sha2 = "0.9.1"
shaderc = "0.7.0"
spirq = "0.4.11"
wgpu = "0.8.0"
lazy_static = "1.4.0"
spirv_headers = "1.4.2"

[features]
default = []
dynamic_shaders = []
